##Import Libraries

In [ ]:
import pandas as pd
import numpy as np

##Import Data

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Churn Modeling/Churn_Modelling.csv')

##**EDA**

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
data['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [ ]:
data.drop_duplicates()

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [ ]:
data[['Gender','Exited']]

Gender  Exited
0     Female       1
1     Female       0
2     Female       1
3     Female       0
4     Female       0
...      ...     ...
9995    Male       0
9996    Male       0
9997  Female       1
9998    Male       1
9999  Female       0

[10000 rows x 2 columns]

In [ ]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
data.shape

(10000, 14)

In [ ]:
data_new=data.drop(['RowNumber','CustomerId','Surname'],axis=1)


In [ ]:
data_new=pd.get_dummies(data_new,drop_first=True)

In [ ]:
data_new

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1                  0   
1                  1        112542.58       0                  0   
2                  0        113931.57       1                  0   
3                  0         93826.63       0                  0   
4                  1         79084.10       0                  0   
...              ...              ...     ...                ...   
9995               0         96270.64       0                  0   
9996               1        101699.77       0                  0   
9997               1         42085.58       1                  0   
9998               0         92888.52       1                  1   
9999               0         38190.78       0                  0   

      Geography_Spain  Gender_Male  
0                   0            0  
1                   1            0  
2                   0            0  
3                   0            0  
4                   1            0  
...               ...          ...  
9995                0            1  
9996                0            1  
9997                0            0  
9998                0            1  
9999                0            0  

[10000 rows x 12 columns]

In [ ]:
y=data['Exited']
x=data_new.drop(['Exited'],axis=1)

In [ ]:
x.shape

(10000, 11)

##**Splitting Data**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test , y_train, y_test = train_test_split(x.values,y.values,test_size=0.25,random_state=123,stratify=y.values)

In [ ]:
from imblearn.over_sampling import SMOTE

method= SMOTE()
X_resampled, y_resampled = method.fit_resample(X_train, y_train)

##**Training Model**

###**1. Logistic Regression**

In [ ]:
#logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

model=LogisticRegression()
model.fit(X_resampled,y_resampled)
predicted=model.predict(X_test)
print('Classification report:\n', classification_report(y_test, predicted))
conf_mat = confusion_matrix(y_true=y_test, y_pred=predicted)
print('Confusion matrix:\n', conf_mat)
print('Share of Non-Fraud in Test Data:', 1-round(y_test.sum()/len(y_test),4))

Classification report:
               precision    recall  f1-score   support

           0       0.88      0.66      0.75      1991
           1       0.32      0.65      0.43       509

    accuracy                           0.65      2500
   macro avg       0.60      0.65      0.59      2500
weighted avg       0.77      0.65      0.69      2500

Confusion matrix:
 [[1305  686]
 [ 180  329]]
Share of Non-Fraud in Test Data: 0.7964


##**2. Random Forest**

In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier(random_state=5)
model2.fit(X_resampled,y_resampled)
predicted=model2.predict(X_test)
print('Classification report:\n', classification_report(y_test, predicted))
conf_mat = confusion_matrix(y_true=y_test, y_pred=predicted)
print('Confusion matrix:\n', conf_mat)
print('Share of Non-Fraud in Test Data:', 1-round(y_test.sum()/len(y_test),4))

Classification report:
               precision    recall  f1-score   support

           0       0.89      0.95      0.92      1991
           1       0.73      0.54      0.62       509

    accuracy                           0.86      2500
   macro avg       0.81      0.74      0.77      2500
weighted avg       0.86      0.86      0.86      2500

Confusion matrix:
 [[1887  104]
 [ 234  275]]
Share of Non-Fraud in Test Data: 0.7964


##**3. SGD Classifier**

In [ ]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(random_state=42)
sgd.fit(X_resampled, y_resampled)
predicted_SGD=sgd.predict(X_test)
print('Classification report:\n', classification_report(y_test, predicted_SGD))
conf_mat = confusion_matrix(y_true=y_test, y_pred=predicted_SGD)
print('Confusion matrix:\n', conf_mat)
print('Share of Non-Fraud in Test Data:', 1-round(y_test.sum()/len(y_test),4))

Classification report:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1991
           1       0.00      0.00      0.00       509

    accuracy                           0.80      2500
   macro avg       0.40      0.50      0.44      2500
weighted avg       0.63      0.80      0.71      2500

Confusion matrix:
 [[1991    0]
 [ 509    0]]
Share of Non-Fraud in Test Data: 0.7964


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


##**4. SVC Classifier**

In [ ]:
from sklearn.svm import SVC
svc_classifier = SVC(kernel='linear')
svc_classifier.fit(X_resampled, y_resampled)


# Make Prediction & print the result
predicted_SVM = svc_classifier.predict(X_test)
print(classification_report(y_test,predicted_SVM))
conf_mat_SVM = confusion_matrix(y_true=y_test, y_pred=predicted_SVM)
print('Confusion matrix:\n', conf_mat_SVM)

              precision    recall  f1-score   support

           0       0.90      0.68      0.77      1991
           1       0.36      0.71      0.48       509

    accuracy                           0.69      2500
   macro avg       0.63      0.69      0.63      2500
weighted avg       0.79      0.69      0.71      2500

Confusion matrix:
 [[1354  637]
 [ 150  359]]


##Following was the Result

---
###Random Forrest performs the best on the data that has less number of positive results.

---
###SVC performs relatively goog than other algos along with Logistic regression

---

###SGD Classifier performs the worst for imbalanced data


